#pragma once

//
// This file contains all IDs of game assets 
//

#define ID_TEX_MARIO 0
#define ID_TEX_ENEMY 10
#define ID_TEX_MISC 20


#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPA	3
#define OBJECT_TYPE_COIN 4
#define OBJECT_TYPE_PLATFORM 5
#define OBJECT_TYPE_BACKGROUND 6
#define OBJECT_TYPE_BACKGROUND_CLOUD 7
#define OBJECT_TYPE_BOX 8
#define OBJECT_TYPE_SIDE_COLLIDABLE_PLATFORM 9
#define OBJECT_TYPE_BLOCK_PLATFORM 10
#define OBJECT_TYPE_QUESTION_BLOCK 11
#define OBJECT_TYPE_PIPE 12
#define OBJECT_TYPE_PIRANHA_PLANT 13
#define OBJECT_TYPE_LIFT	14
#define OBJECT_TYPE_PORTAL	50


#pragma region MARIO 

#define ID_SPRITE_MARIO 10000
#define ID_SPRITE_MARIO_BIG (ID_SPRITE_MARIO + 1000)
#define ID_SPRITE_MARIO_BIG_IDLE (ID_SPRITE_MARIO_BIG + 100)
#define ID_SPRITE_MARIO_BIG_IDLE_LEFT (ID_SPRITE_MARIO_BIG_IDLE + 10)
#define ID_SPRITE_MARIO_BIG_IDLE_RIGHT (ID_SPRITE_MARIO_BIG_IDLE + 20)

#define ID_SPRITE_MARIO_BIG_WALKING (ID_SPRITE_MARIO_BIG + 200)
#define ID_SPRITE_MARIO_BIG_WALKING_LEFT (ID_SPRITE_MARIO_BIG_WALKING + 10)
#define ID_SPRITE_MARIO_BIG_WALKING_RIGHT (ID_SPRITE_MARIO_BIG_WALKING + 20)
#define ID_SPRITE_MARIO_BIG_RUNNING (ID_SPRITE_MARIO_BIG + 300)
#define ID_SPRITE_MARIO_BIG_RUNNING_LEFT (ID_SPRITE_MARIO_BIG_RUNNING + 10)
#define ID_SPRITE_MARIO_BIG_RUNNING_RIGHT (ID_SPRITE_MARIO_BIG_RUNNING + 20)
#define ID_SPRITE_MARIO_BIG_JUMP (ID_SPRITE_MARIO_BIG + 400)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK (ID_SPRITE_MARIO_BIG_JUMP + 10)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_LEFT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN (ID_SPRITE_MARIO_BIG_JUMP + 20)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_LEFT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_BIG_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_BIG_JUMP_RUN + 6)
#define ID_SPRITE_MARIO_BIG_SIT (ID_SPRITE_MARIO_BIG + 500)
#define ID_SPRITE_MARIO_BIG_SIT_LEFT (ID_SPRITE_MARIO_BIG_SIT + 10)
#define ID_SPRITE_MARIO_BIG_SIT_RIGHT (ID_SPRITE_MARIO_BIG_SIT + 20)
#define ID_SPRITE_MARIO_BIG_BRACE (ID_SPRITE_MARIO_BIG + 600)
#define ID_SPRITE_MARIO_BIG_BRACE_LEFT (ID_SPRITE_MARIO_BIG_BRACE + 10)
#define ID_SPRITE_MARIO_BIG_BRACE_RIGHT (ID_SPRITE_MARIO_BIG_BRACE + 20)

#define ID_SPRITE_MARIO_DIE (ID_SPRITE_MARIO + 3000)

#define ID_SPRITE_MARIO_SMALL (ID_SPRITE_MARIO + 2000)
#define ID_SPRITE_MARIO_SMALL_IDLE (ID_SPRITE_MARIO_SMALL + 100)
#define ID_SPRITE_MARIO_SMALL_IDLE_LEFT (ID_SPRITE_MARIO_SMALL_IDLE + 10)
#define ID_SPRITE_MARIO_SMALL_IDLE_RIGHT (ID_SPRITE_MARIO_SMALL_IDLE + 20)

#define ID_SPRITE_MARIO_SMALL_WALKING (ID_SPRITE_MARIO_SMALL + 200)
#define ID_SPRITE_MARIO_SMALL_WALKING_LEFT (ID_SPRITE_MARIO_SMALL_WALKING + 10)
#define ID_SPRITE_MARIO_SMALL_WALKING_RIGHT (ID_SPRITE_MARIO_SMALL_WALKING + 20)
#define ID_SPRITE_MARIO_SMALL_RUNNING (ID_SPRITE_MARIO_SMALL + 300)
#define ID_SPRITE_MARIO_SMALL_RUNNING_LEFT (ID_SPRITE_MARIO_SMALL_RUNNING + 10)
#define ID_SPRITE_MARIO_SMALL_RUNNING_RIGHT (ID_SPRITE_MARIO_SMALL_RUNNING + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP (ID_SPRITE_MARIO_SMALL + 400)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK (ID_SPRITE_MARIO_SMALL_JUMP + 10)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_WALK_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_WALK + 6)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN (ID_SPRITE_MARIO_SMALL_JUMP + 20)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_LEFT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 2)
#define ID_SPRITE_MARIO_SMALL_JUMP_RUN_RIGHT (ID_SPRITE_MARIO_SMALL_JUMP_RUN + 6)

#define ID_SPRITE_MARIO_SMALL_SIT (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_SIT_LEFT (ID_SPRITE_MARIO_SMALL_SIT + 10)
#define ID_SPRITE_MARIO_SMALL_SIT_RIGHT (ID_SPRITE_MARIO_SMALL_SIT + 20)

#define ID_SPRITE_MARIO_SMALL_BRACE (ID_SPRITE_MARIO_SMALL + 500)
#define ID_SPRITE_MARIO_SMALL_BRACE_LEFT (ID_SPRITE_MARIO_SMALL_BRACE + 10)
#define ID_SPRITE_MARIO_SMALL_BRACE_RIGHT (ID_SPRITE_MARIO_SMALL_BRACE + 20)

#pragma endregion 

#pragma region BRICK
#define ID_SPRITE_BRICK 20000
#pragma endregion

#pragma region GOOMBA
#define ID_SPRITE_GOOMBA 30000
#define ID_SPRITE_GOOMBA_WALK (ID_SPRITE_GOOMBA + 1000)
#define ID_SPRITE_GOOMBA_DIE (ID_SPRITE_GOOMBA + 2000)
#pragma endregion

#pragma region COIN
#define ID_SPRITE_COIN 40000
#pragma endregion

#pragma region CLOUD
#define ID_SPRITE_CLOUD 50000
#define ID_SPRITE_CLOUD_BEGIN (ID_SPRITE_CLOUD+1000)
#define ID_SPRITE_CLOUD_MIDDLE (ID_SPRITE_CLOUD+2000)
#define ID_SPRITE_CLOUD_END (ID_SPRITE_CLOUD+3000)
#pragma endregion

#pragma region BOX
#define SPRITE_ID_BOX_PINK_TOP_LEFT 111001
#define SPRITE_ID_BOX_PINK_TOP_MIDDLE 111002
#define SPRITE_ID_BOX_PINK_TOP_RIGHT 111003
#define SPRITE_ID_BOX_PINK_MIDDLE_LEFT 111004
#define SPRITE_ID_BOX_PINK_MIDDLE 111005
#define SPRITE_ID_BOX_PINK_MIDDLE_RIGHT 111006
#define SPRITE_ID_BOX_PINK_BOTTOM_LEFT 111007
#define SPRITE_ID_BOX_PINK_BOTTOM_MIDDLE 111008
#define SPRITE_ID_BOX_PINK_BOTTOM_RIGHT 111009

#define SPRITE_ID_BOX_BLUE_TOP_LEFT 112001
#define SPRITE_ID_BOX_BLUE_TOP_MIDDLE 112002
#define SPRITE_ID_BOX_BLUE_TOP_RIGHT 112003
#define SPRITE_ID_BOX_BLUE_MIDDLE_LEFT 112004
#define SPRITE_ID_BOX_BLUE_MIDDLE 112005
#define SPRITE_ID_BOX_BLUE_MIDDLE_RIGHT 112006
#define SPRITE_ID_BOX_BLUE_BOTTOM_LEFT 112007
#define SPRITE_ID_BOX_BLUE_BOTTOM_MIDDLE 112008
#define SPRITE_ID_BOX_BLUE_BOTTOM_RIGHT 112009

#define SPRITE_ID_BOX_GREEN_TOP_LEFT 113001
#define SPRITE_ID_BOX_GREEN_TOP_MIDDLE 113002
#define SPRITE_ID_BOX_GREEN_TOP_RIGHT 113003
#define SPRITE_ID_BOX_GREEN_MIDDLE_LEFT 113004
#define SPRITE_ID_BOX_GREEN_MIDDLE 113005
#define SPRITE_ID_BOX_GREEN_MIDDLE_RIGHT 113006
#define SPRITE_ID_BOX_GREEN_BOTTOM_LEFT 113007
#define SPRITE_ID_BOX_GREEN_BOTTOM_MIDDLE 113008
#define SPRITE_ID_BOX_GREEN_BOTTOM_RIGHT 113009

#define SPRITE_ID_BOX_WHITE_TOP_LEFT 114001
#define SPRITE_ID_BOX_WHITE_TOP_MIDDLE 114002
#define SPRITE_ID_BOX_WHITE_TOP_RIGHT 114003
#define SPRITE_ID_BOX_WHITE_MIDDLE_LEFT 114004
#define SPRITE_ID_BOX_WHITE_MIDDLE 114005
#define SPRITE_ID_BOX_WHITE_MIDDLE_RIGHT 114006
#define SPRITE_ID_BOX_WHITE_BOTTOM_LEFT 114007
#define SPRITE_ID_BOX_WHITE_BOTTOM_MIDDLE 114008
#define SPRITE_ID_BOX_WHITE_BOTTOM_RIGHT 114009

#define SPRITE_ID_BOX_SHADOW_TOP_RIGHT 115001
#define SPRITE_ID_BOX_SHADOW_MIDDLE 115002
#define SPRITE_ID_BOX_SHADOW_BOTTOM_LEFT 115003
#define SPRITE_ID_BOX_SHADOW_BOTTOM_RIGHT 115004
#pragma endregion

#pragma region FLYING_SCORE
#define SPRITE_ID_FLYING_SCORE_100 160001
#define SPRITE_ID_FLYING_SCORE_200 160002
#define SPRITE_ID_FLYING_SCORE_400 160003
#define SPRITE_ID_FLYING_SCORE_800 160004
#define SPRITE_ID_FLYING_SCORE_1000 160005
#define SPRITE_ID_FLYING_SCORE_2000 160006
#define SPRITE_ID_FLYING_SCORE_4000 160007
#define SPRITE_ID_FLYING_SCORE_8000 160008
#pragma endregion