#pragma once

#include "GameObject.h"

#define BLOCK_WIDTH 16
#define BLOCK_HEIGHT 16

#define SPRITE_ID_BLOCK_PINK_TOP_LEFT 111001
#define SPRITE_ID_BLOCK_PINK_TOP_MIDDLE 111002
#define SPRITE_ID_BLOCK_PINK_TOP_RIGHT 111003
#define SPRITE_ID_BLOCK_PINK_MIDDLE_LEFT 111004
#define SPRITE_ID_BLOCK_PINK_MIDDLE 111005
#define SPRITE_ID_BLOCK_PINK_MIDDLE_RIGHT 111006
#define SPRITE_ID_BLOCK_PINK_BOTTOM_LEFT 111007
#define SPRITE_ID_BLOCK_PINK_BOTTOM_MIDDLE 111008
#define SPRITE_ID_BLOCK_PINK_BOTTOM_RIGHT 111009

#define SPRITE_ID_BLOCK_BLUE_TOP_LEFT 112001
#define SPRITE_ID_BLOCK_BLUE_TOP_MIDDLE 112002
#define SPRITE_ID_BLOCK_BLUE_TOP_RIGHT 112003
#define SPRITE_ID_BLOCK_BLUE_MIDDLE_LEFT 112004
#define SPRITE_ID_BLOCK_BLUE_MIDDLE 112005
#define SPRITE_ID_BLOCK_BLUE_MIDDLE_RIGHT 112006
#define SPRITE_ID_BLOCK_BLUE_BOTTOM_LEFT 112007
#define SPRITE_ID_BLOCK_BLUE_BOTTOM_MIDDLE 112008
#define SPRITE_ID_BLOCK_BLUE_BOTTOM_RIGHT 112009

#define SPRITE_ID_BLOCK_GREEN_TOP_LEFT 113001
#define SPRITE_ID_BLOCK_GREEN_TOP_MIDDLE 113002
#define SPRITE_ID_BLOCK_GREEN_TOP_RIGHT 113003
#define SPRITE_ID_BLOCK_GREEN_MIDDLE_LEFT 113004
#define SPRITE_ID_BLOCK_GREEN_MIDDLE 113005
#define SPRITE_ID_BLOCK_GREEN_MIDDLE_RIGHT 113006
#define SPRITE_ID_BLOCK_GREEN_BOTTOM_LEFT 113007
#define SPRITE_ID_BLOCK_GREEN_BOTTOM_MIDDLE 113008
#define SPRITE_ID_BLOCK_GREEN_BOTTOM_RIGHT 113009

#define SPRITE_ID_BLOCK_WHITE_TOP_LEFT 114001
#define SPRITE_ID_BLOCK_WHITE_TOP_MIDDLE 114002
#define SPRITE_ID_BLOCK_WHITE_TOP_RIGHT 114003
#define SPRITE_ID_BLOCK_WHITE_MIDDLE_LEFT 114004
#define SPRITE_ID_BLOCK_WHITE_MIDDLE 114005
#define SPRITE_ID_BLOCK_WHITE_MIDDLE_RIGHT 114006
#define SPRITE_ID_BLOCK_WHITE_BOTTOM_LEFT 114007
#define SPRITE_ID_BLOCK_WHITE_BOTTOM_MIDDLE 114008
#define SPRITE_ID_BLOCK_WHITE_BOTTOM_RIGHT 114009

#define BLOCK_SHADOW_WIDTH 8
#define BLOCK_SHADOW_HEIGHT 8

#define SPRITE_ID_BLOCK_SHADOW_TOP_RIGHT 115001
#define SPRITE_ID_BLOCK_SHADOW_MIDDLE 115002
#define SPRITE_ID_BLOCK_SHADOW_BOTTOM_LEFT 115003
#define SPRITE_ID_BLOCK_SHADOW_BOTTOM_RIGHT 115004

class CBlock : public CGameObject
{
protected:
	int cell_width = BLOCK_WIDTH, cell_height = BLOCK_HEIGHT;
	int length_width, length_height;				// Unit: cell 
	int color;	// 0: pink; 1: blue; 2: green; 3: white;

public:
	CBlock(float x, float y, int length_width, int length_height, int color) : CGameObject(x, y)
	{
		this->length_width = length_width;
		this->length_height = length_height;
		this->color = color;
	}

	void Render();
	void Update(DWORD dt) {}
	void GetBoundingBox(float& l, float& t, float& r, float& b);
	void RenderBoundingBox();

	int IsDirectionColliable(float nx, float ny);
};

typedef CBlock* LPBLOCK;